workflows:
  react-native:
    name: DynaFood App
    environment:
      vars:
        XCODE_WORKSPACE: "{{}}"
        XCODE_SCHEME: "{{}}"
      node: latest
    scripts:
      - npm install
      - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - |
        # build Android
        cd android
        ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk