workflows:
  react-native:
    name: DynaFood App
    environment:
      node: latest
    scripts:
      - npm install -g expo-cli
      - |
        # build and start
        npm install --legacy-peer-deps
        npm start
        npm stop
      - npm test
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true