version: '2.4'

services:
  dynafood:
    build:
      context: .
      args:
        - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./App:/opt/dynafood/app:delegated
      - ./App/package.json:/opt/dynafood/package.json
      - ./App/package-lock.json:/opt/dynafood/package-lock.json
      - notused:/opt/react_native_app/app/node_modules
    healthcheck:
      disable: true
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.50.198
      - NODE_ENV=development
    extra_hosts:
      - "devserver:192.168.50.198"

volumes:
  notused: