FROM node:latest

WORKDIR /usr/src/app
COPY package*.json ./

COPY . .
RUN npm install
EXPOSE 8080
#ENV PORT 8080
#CMD ["node"]
# server.js


#WORKDIR /usr/src/app/src


#RUN npm install

#COPY . .

#EXPOSE 8080

#CMD [ "ls"]

#CMD ["npm", "start" , "server.js"]